// // <auto-generated>
// // THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// // </auto-generated>
//
// #pragma warning disable 618
// #pragma warning disable 612
// #pragma warning disable 414
// #pragma warning disable 168
//
// #pragma warning disable SA1200 // Using directives should be placed correctly
// #pragma warning disable SA1312 // Variable names should begin with lower-case letter
// #pragma warning disable SA1649 // File name should match first type name
//
// namespace MessagePack.Resolvers
// {
//     using System;
//
//     public class GeneratedResolver : global::MessagePack.IFormatterResolver
//     {
//         public static readonly global::MessagePack.IFormatterResolver Instance = new GeneratedResolver();
//
//         private GeneratedResolver()
//         {
//         }
//
//         public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
//         {
//             return FormatterCache<T>.Formatter;
//         }
//
//         private static class FormatterCache<T>
//         {
//             internal static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> Formatter;
//
//             static FormatterCache()
//             {
//                 var f = GeneratedResolverGetFormatterHelper.GetFormatter(typeof(T));
//                 if (f != null)
//                 {
//                     Formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)f;
//                 }
//             }
//         }
//     }
//
//     internal static class GeneratedResolverGetFormatterHelper
//     {
//         private static readonly global::System.Collections.Generic.Dictionary<Type, int> lookup;
//
//         static GeneratedResolverGetFormatterHelper()
//         {
//             lookup = new global::System.Collections.Generic.Dictionary<Type, int>(1)
//             {
//                 { typeof(global::Texture2DPack), 0 },
//             };
//         }
//
//         internal static object GetFormatter(Type t)
//         {
//             int key;
//             if (!lookup.TryGetValue(t, out key))
//             {
//                 return null;
//             }
//
//             switch (key)
//             {
//                 case 0: return new MessagePack.Formatters.Texture2DPackFormatter();
//                 default: return null;
//             }
//         }
//     }
// }
//
// #pragma warning restore 168
// #pragma warning restore 414
// #pragma warning restore 618
// #pragma warning restore 612
//
// #pragma warning restore SA1312 // Variable names should begin with lower-case letter
// #pragma warning restore SA1200 // Using directives should be placed correctly
// #pragma warning restore SA1649 // File name should match first type name
//
//
//
//
// // <auto-generated>
// // THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// // </auto-generated>
//
// #pragma warning disable 618
// #pragma warning disable 612
// #pragma warning disable 414
// #pragma warning disable 168
//
// #pragma warning disable SA1129 // Do not use default value type constructor
// #pragma warning disable SA1200 // Using directives should be placed correctly
// #pragma warning disable SA1309 // Field names should not begin with underscore
// #pragma warning disable SA1312 // Variable names should begin with lower-case letter
// #pragma warning disable SA1403 // File may only contain a single namespace
// #pragma warning disable SA1649 // File name should match first type name
//
// namespace MessagePack.Formatters
// {
//     using System;
//     using System.Buffers;
//     using MessagePack;
//
//     public sealed class Texture2DPackFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Texture2DPack>
//     {
//
//
//         public void Serialize(ref MessagePackWriter writer, global::Texture2DPack value, global::MessagePack.MessagePackSerializerOptions options)
//         {
//             if (value == null)
//             {
//                 writer.WriteNil();
//                 return;
//             }
//
//             IFormatterResolver formatterResolver = options.Resolver;
//             writer.WriteArrayHeader(5);
//             formatterResolver.GetFormatterWithVerify<byte[]>().Serialize(ref writer, value.rawData, options);
//             writer.Write(value.width);
//             writer.Write(value.height);
//             writer.Write(value.format);
//             writer.Write(value.flags);
//         }
//
//         public global::Texture2DPack Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
//         {
//             if (reader.TryReadNil())
//             {
//                 return null;
//             }
//
//             options.Security.DepthStep(ref reader);
//             IFormatterResolver formatterResolver = options.Resolver;
//             var length = reader.ReadArrayHeader();
//             var __rawData__ = default(byte[]);
//             var __width__ = default(int);
//             var __height__ = default(int);
//             var __format__ = default(int);
//             var __flags__ = default(bool);
//
//             for (int i = 0; i < length; i++)
//             {
//                 var key = i;
//
//                 switch (key)
//                 {
//                     case 0:
//                         __rawData__ = formatterResolver.GetFormatterWithVerify<byte[]>().Deserialize(ref reader, options);
//                         break;
//                     case 1:
//                         __width__ = reader.ReadInt32();
//                         break;
//                     case 2:
//                         __height__ = reader.ReadInt32();
//                         break;
//                     case 3:
//                         __format__ = reader.ReadInt32();
//                         break;
//                     case 4:
//                         __flags__ = reader.ReadBoolean();
//                         break;
//                     default:
//                         reader.Skip();
//                         break;
//                 }
//             }
//
//             var ____result = new global::Texture2DPack();
//             ____result.rawData = __rawData__;
//             ____result.width = __width__;
//             ____result.height = __height__;
//             ____result.format = __format__;
//             ____result.flags = __flags__;
//             reader.Depth--;
//             return ____result;
//         }
//     }
// }
//
// #pragma warning restore 168
// #pragma warning restore 414
// #pragma warning restore 618
// #pragma warning restore 612
//
// #pragma warning restore SA1129 // Do not use default value type constructor
// #pragma warning restore SA1200 // Using directives should be placed correctly
// #pragma warning restore SA1309 // Field names should not begin with underscore
// #pragma warning restore SA1312 // Variable names should begin with lower-case letter
// #pragma warning restore SA1403 // File may only contain a single namespace
// #pragma warning restore SA1649 // File name should match first type name
//
